version: "3"
services: 
    jenkins:
        image: jenkins/jenkins:lts
        ports:
            - "8080:8080"
        volumes: 
            - ".dev/jenkins_home:/var/jenkins_home"
    
    statsd-exporter:
        image: prom/statsd-exporter
        ports:
            - "8125:9125/udp"
            - "8083:9102"
        expose:
            - "9000"
    
    prometheus:
        image: prom/prometheus
        ports:
            - "8081:9090"
        links:
            - "statsd-exporter:statsd.service"
        volumes:
            - ".dev/prometheus.yml:/etc/prometheus/prometheus.yml:ro"

    grafana:
        image: grafana/grafana
        ports:
            - "8082:3000"
        links: 
            - "prometheus:prometheus.service"