###
GET http://localhost:8080/job/test-pipeline/api/json?tree=builds[number,timestamp,result,duration,url]{0,50}
Accept: application/json
Authorization: Basic YWRtaW46MDQwOWFkNDk4MTcwNGEzZWEyMzc1MWY5NTZkZWRlOTA=

### 
GET http://localhost:8080/api/json?tree=jobs[name]{0,50}
Accept: application/json
Authorization: Basic YWRtaW46MDQwOWFkNDk4MTcwNGEzZWEyMzc1MWY5NTZkZWRlOTA=